name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 1.0.1
homepage: https://github.com/cachapa/firedart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  grpc: ^2.8.0
  protobuf: ^1.1.0
  fixnum: ^0.10.11

dev_dependencies:
  test: ^1.6.4
  pedantic: ^1.9.0
